---
abstract: 'A minimal and fast alternative to L<Linux::Smaps>'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Linux-Smaps-Tiny
no_index:
  directory:
    - t
requires:
  Exporter: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Linux-Smaps-Tiny
  homepage: http://search.cpan.org/dist/Linux-Smaps-Tiny/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/avar/linux-smaps-tiny.git
version: 0.05
x_authority: cpan:AVAR
